name: My First WorkFlow

on: 
  push: 
    branches: 
      - 'main'
  workflow_dispatch: # <--- ADD THIS LINE to see the "Run workflow" button

jobs:
  first_job:         
    name: My First Job
    runs-on: ubuntu-latest
    steps:
      - name: Greet the User
        run: |
          echo "Hello World from ${{ github.actor }}."
          echo "Current Branch is '${{ github.ref }}'."
        shell: bash

      - name: Checkout 
        uses: actions/checkout@v6.0.2 # Note: v4 is the current stable version

      - name: Run Tree 
        run: |
          sudo apt-get install -y tree
          tree
