# My First WorkFlow
name: My First WorkFlow
on: 
  push: 
    branches: 
      - 'main'
      - 'release/**' # Added space after dash
    paths: 
      - 'ActionsCookBook/.github/workflows'
      - 'docs/**'    # Added space after dash

jobs:
  first_job:         
    name: My First Job
    runs-on: ubuntu-latest
    steps:
      - name: Greet the User
        run: |
          echo "Hello World from ${{ github.actor }}."
          echo "Current Branch is '${{ github.ref }}'."
        shell: bash

      - name: Checkout 
        uses: actions/checkout@v6.0.2

      - name: Run Tree 
        run: tree
  
